### ISSUE TITLE
It seems that this implementation does not need intrinsic matrix, either

### ISSUE THREAD

**Issue by captainst** [AbhinavTuli/SpaceCarving#1]
Very interesting implementation. I see the code using 2 orthogonal images were taken from the same distance, with same focal length. So there is no need to consider a "visual hull", you simply carved away "orthogonally" the cube, thus results in a straight forward model.

So, I think that this implementation does not need neither extrinsic, nor intrinsic matrix.

**Comment by AbhinavTuli** [comment]
Agreed, just the images are needed. Edited the readme.
